config/routes.rb
Rails.application.routes.draw do
 
  resources :pre_requisitos
  resources :materia
  resources :turmas
  resources :professors
  resources :alunos
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/turma.rb
class Turma < ApplicationRecord

    belongs_to :materia # Uma turma está associada a uma matéria
    belongs_to :professor # Uma turma é menistrada por um professor

    has_many :aluno # Uma turma pode ter vários alunos inscritos

end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:sigla, :dias_da_semana, :horario, :status)
    end
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla %>
  </div>

  <div class="field">
    <%= form.label :dias_da_semana %>
    <%= form.text_field :dias_da_semana %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_field :horario %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Sigla</th>
      <th>Dias da semana</th>
      <th>Horario</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.sigla %></td>
        <td><%= turma.dias_da_semana %></td>
        <td><%= turma.horario %></td>
        <td><%= turma.status %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sigla:</strong>
  <%= @turma.sigla %>
</p>

<p>
  <strong>Dias da semana:</strong>
  <%= @turma.dias_da_semana %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @turma.horario %>
</p>

<p>
  <strong>Status:</strong>
  <%= @turma.status %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>