config/routes.rb
Rails.application.routes.draw do
 
  resources :pre_requisitos
  resources :materia
  resources :turmas
  resources :professors
  resources :alunos
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord


    has_many :turma # Um aluno pode se inscrever em várias turmas
    has_many :usuarios, as: :userable # usuario > aluno


end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:cr, :matricula)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cr %>
    <%= form.text_field :cr %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.number_field :matricula %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Cr</th>
      <th>Matricula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.cr %></td>
        <td><%= aluno.matricula %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cr:</strong>
  <%= @aluno.cr %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @aluno.matricula %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>