config/routes.rb
Rails.application.routes.draw do
 
  resources :pre_requisitos
  resources :materia
  resources :turmas
  resources :professors
  resources :alunos
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pre_requisito.rb
class Prerequisito < ApplicationRecord
  belongs_to :materia_one, :foreign_key => :id, class_name: "Materia"
  belongs_to :materia_two, :foreign_key => :materia_id, class_name: "Materia"


 
end

app/controllers/pre_requisitos_controller.rb
class PreRequisitosController < ApplicationController
  before_action :set_pre_requisito, only: [:show, :edit, :update, :destroy]

  # GET /pre_requisitos
  # GET /pre_requisitos.json
  def index
    @pre_requisitos = PreRequisito.all
  end

  # GET /pre_requisitos/1
  # GET /pre_requisitos/1.json
  def show
  end

  # GET /pre_requisitos/new
  def new
    @pre_requisito = PreRequisito.new
  end

  # GET /pre_requisitos/1/edit
  def edit
  end

  # POST /pre_requisitos
  # POST /pre_requisitos.json
  def create
    @pre_requisito = PreRequisito.new(pre_requisito_params)

    respond_to do |format|
      if @pre_requisito.save
        format.html { redirect_to @pre_requisito, notice: 'Pre requisito was successfully created.' }
        format.json { render :show, status: :created, location: @pre_requisito }
      else
        format.html { render :new }
        format.json { render json: @pre_requisito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pre_requisitos/1
  # PATCH/PUT /pre_requisitos/1.json
  def update
    respond_to do |format|
      if @pre_requisito.update(pre_requisito_params)
        format.html { redirect_to @pre_requisito, notice: 'Pre requisito was successfully updated.' }
        format.json { render :show, status: :ok, location: @pre_requisito }
      else
        format.html { render :edit }
        format.json { render json: @pre_requisito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_requisitos/1
  # DELETE /pre_requisitos/1.json
  def destroy
    @pre_requisito.destroy
    respond_to do |format|
      format.html { redirect_to pre_requisitos_url, notice: 'Pre requisito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pre_requisito
      @pre_requisito = PreRequisito.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pre_requisito_params
      params.require(:pre_requisito).permit(:id_id, :materia_id, :accept)
    end
end

app/helpers/pre_requisitos_helper.rb
module PreRequisitosHelper
end

app/views/pre_requisitos/_form.html.erb
<%= form_with(model: pre_requisito, local: true) do |form| %>
  <% if pre_requisito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pre_requisito.errors.count, "error") %> prohibited this pre_requisito from being saved:</h2>

      <ul>
      <% pre_requisito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_id %>
    <%= form.text_field :id_id %>
  </div>

  <div class="field">
    <%= form.label :materia_id %>
    <%= form.number_field :materia_id %>
  </div>

  <div class="field">
    <%= form.label :accept %>
    <%= form.check_box :accept %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pre_requisitos/edit.html.erb
<h1>Editing Pre Requisito</h1>

<%= render 'form', pre_requisito: @pre_requisito %>

<%= link_to 'Show', @pre_requisito %> |
<%= link_to 'Back', pre_requisitos_path %>

app/views/pre_requisitos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pre Requisitos</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Materia</th>
      <th>Accept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pre_requisitos.each do |pre_requisito| %>
      <tr>
        <td><%= pre_requisito.id %></td>
        <td><%= pre_requisito.materia_id %></td>
        <td><%= pre_requisito.accept %></td>
        <td><%= link_to 'Show', pre_requisito %></td>
        <td><%= link_to 'Edit', edit_pre_requisito_path(pre_requisito) %></td>
        <td><%= link_to 'Destroy', pre_requisito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pre Requisito', new_pre_requisito_path %>

app/views/pre_requisitos/new.html.erb
<h1>New Pre Requisito</h1>

<%= render 'form', pre_requisito: @pre_requisito %>

<%= link_to 'Back', pre_requisitos_path %>

app/views/pre_requisitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @pre_requisito.id %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @pre_requisito.materia_id %>
</p>

<p>
  <strong>Accept:</strong>
  <%= @pre_requisito.accept %>
</p>

<%= link_to 'Edit', edit_pre_requisito_path(@pre_requisito) %> |
<%= link_to 'Back', pre_requisitos_path %>