config/routes.rb
Rails.application.routes.draw do
 
  resources :pre_requisitos
  resources :materia
  resources :turmas
  resources :professors
  resources :alunos
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord

    has_many :turma # Um professor pode ministrar em várias turmas
    has_many :materia # Um professor pode ser licenciado em várias matérias
    has_many :usuarios, as: :userable # usuario > professor

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.require(:professor).permit(:matricula)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.number_field :matricula %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.matricula %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @professor.matricula %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>